# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-api-deployment
  labels:
    app: spam-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spam-api
  template:
    metadata:
      labels:
        app: spam-api
    spec:
      containers:
      - name: spam-api
        image: saikalyan1210/spam-api:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  # application port
        - containerPort: 8000  # Prometheus metrics port
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
