apiVersion: batch/v1
kind: CronJob
metadata:
  name: spam-retrain
spec:
  schedule: "0 2 * * *"     # every day at 02:00
  concurrencyPolicy: Forbid # don’t overlap runs
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: retrain
            image: saikalyan1210/spam-api:latest
            command:
              - curl
              - -X
              - POST
              - http://spam-api-service:80/retrain
