# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spam-api-service
spec:
  type: NodePort
  selector:
    app: spam-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
      nodePort: 30080
